###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
###############################################################################
- name: Trackpad - enable tap to click for builtin
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    type: bool
    value: "{{ tapToClick }}"
    state: present

- name: Trackpad - enable tap to click for bluetooth
  community.general.osx_defaults:
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: Clicking
    type: bool
    value: "{{ tapToClick }}"
    state: present

- name: Trackpad - host tapbehavior
  community.general.osx_defaults:
    domain: NSGlobalDomain
    host: currentHost
    key: com.apple.mouse.tapBehavior
    type: int
    value: "{{ '1' if tapToClick else '0' }}"
    state: present

- name: Trackpad - host tapbehavior
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: int
    value: "{{ '1' if tapToClick else '0' }}"
    state: present

- name: Enable full keyboard access for all controls
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    type: int
    value: 3
    state: present

- name: Set Language
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleLanguages
    type: array
    value:
      - de
      - en
    state: present

- name: Set Locale
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleLocale
    type: string
    value: "{{ location.locale }}@currency={{ location.currency }}"
    state: present

- name: Set Measurement
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleMeasurementUnits
    type: string
    value: "Centimeters"
    state: present
  when: location.useMetric

- name: Set Metrics Unit
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleMetricUnits
    type: bool
    value: "{{ location.useMetric }}"
    state: present

- name: Show language menu in the top right corner of the boot screen
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.loginwindow
    key: showInputMenu
    type: bool
    value: true
    state: present
